export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FILTER_PRODUCT_BY_TYPE = "FILTER_PRODUCT_BY_TYPE"
export const FILTER_PRODUCT_BY_COLOR = "FILTER_PRODUCT_BY_COLOR"
export const FILTER_PRODUCT_BY_SIZE = "FILTER_PRODUCT_BY_SIZE";
